/********************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ********************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define MCU_as_Master
#define MCU_as_Slave

#include "stm32f103x6.h"
#include "stm32f103x6_gpio_driver.h"
#include "stm32f103x6_EXTI_driver.h"
#include "stm32f103x6_USART_driver.h"
#include "stm32f103x6_SPI_driver.h"
#include "stm32f103x6_I2C_driver.h"
#include "I2C_Slave_EEPROM.h"
#include "lcd.h"
#include "keypad.h"



void clk_init(){
	//Enable clk for GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clk for GPIOB
	RCC_GPIOB_CLK_EN();
	//Enable clk for AFIO
	RCC_AFIO_CLK_EN();

}




int main(void)
{	// initialization
	clk_init();
	EEPROM_Init();

	//test case 1
	uint8_t ch1[] = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	uint8_t ch2[7] = {0};

	EEPROM_Write_NBytes(0xAF, ch1, 7);
	EEPROM_ReadByte(0xAF, ch2, 7);


	//test case 2
	ch1[0] = 0xA;
	ch1[1] = 0xB;
	ch1[2] = 0xC;
	ch1[3] = 0xD;

	EEPROM_Write_NBytes(0xFFF, ch1, 4);
	EEPROM_ReadByte(0xFFF, ch2, 4);
	/* Loop forever */
	while(1){

	}
}

