/********************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ********************************************************************************
*/


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




#include "stm32f103x6.h"
#include "stm32f103x6_gpio_driver.h"


void clk_init(){
	//Enable clk for GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clk for GPIOB
	RCC_GPIOB_CLK_EN();
}

void GPIO_init(){
	GPIO_PinConfig_t PinCfg;

	// configuring pin A1 as floating input
	PinCfg.GPIO_PinNumber = GPIO_Pin_1;
	PinCfg.GPIO_MODE = GPIO_MODE_In_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	// configuring pin B1 as Push Pull output
	PinCfg.GPIO_PinNumber = GPIO_Pin_1;
	PinCfg.GPIO_MODE = GPIO_MODE_Out_PP;
	PinCfg.GPIO_Out_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	// configuring pin A13 as floating input
	PinCfg.GPIO_PinNumber = GPIO_Pin_13;
	PinCfg.GPIO_MODE = GPIO_MODE_In_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	// configuring pin B13 as Push Pull output
	PinCfg.GPIO_PinNumber = GPIO_Pin_13;
	PinCfg.GPIO_MODE = GPIO_MODE_Out_PP;
	PinCfg.GPIO_Out_Speed = GPIO_Speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
}

void wait_ms(uint32_t time){
	volatile uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clk_init();
	GPIO_init();

    /* Loop forever */
	while(1){
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_Pin_1 ) == 0){

			MCAL_GPIO_TogglePin(GPIOB, GPIO_Pin_1);		//toggle led on Pin B1
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_Pin_1) == 0); //single pressing
		}

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_Pin_13) == 1)	//multiple pressing

			MCAL_GPIO_TogglePin(GPIOB, GPIO_Pin_13);//toggle led on Pin B13

		wait_ms(10);
	}
}

