/********************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ********************************************************************************
*/


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




#include "stm32f103x6.h"
#include "stm32f103x6_gpio_driver.h"
#include "lcd.h"
#include  "keypad.h"
#include "stm32f103x6_EXTI_driver.h"


uint8_t IRQ_flag;


void clk_init(){
	//Enable clk for GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clk for GPIOB
	RCC_GPIOB_CLK_EN();
	//Enable clk for AFIO
	RCC_AFIO_CLK_EN();
}
void EXTI9_Callback(void){
	IRQ_flag = 1;
	LCD_WRITE_STRING("Hello My Friend");
	wait_ms(50);
}
//void wait_ms(uint32_t time){
//	volatile uint32_t i,j;
//	for(i=0;i<time;i++)
//		for(j=0;j<255;j++);
//}

int main(void)
{	 // initialization
	clk_init();
	LCD_INIT();
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_Cfg;
	EXTI_Cfg.EXTI_Pin = EXTI9PB9;
	EXTI_Cfg.Trigger_Case = EXTI_Trigger_Rising;
	EXTI_Cfg.P_IRQ_CallBack = EXTI9_Callback;
	EXTI_Cfg.IRQ_En = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTI_Cfg);
	IRQ_flag =1;


    /* Loop forever */
	while(1){
		if(IRQ_flag){
			LCD_clear_screen();
			IRQ_flag =0;
		}

	}
}

